# Generated by Django 4.0.5 on 2022-07-03 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0007_remove_profesor_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Herramientas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('codigo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('funcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameModel(
            old_name='Profesor',
            new_name='Operario',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.AlterModelOptions(
            name='operario',
            options={'verbose_name_plural': 'Operarios'},
        ),
    ]
