# Generated by Django 4.0.5 on 2022-07-05 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoCoderApp', '0009_alter_maquinaria_funcion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operario',
            old_name='profesion',
            new_name='area',
        ),
        migrations.RemoveField(
            model_name='operario',
            name='email',
        ),
    ]
